# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'RNSVG', :path => '../node_modules/react-native-svg'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'CxxBridge',
'DevSupport',
# the following ones are the ones taken from "Libraries" in Xcode:
'RCTAnimation',
'RCTActionSheet',
'RCTBlob',
'RCTGeolocation',
'RCTImage',
'RCTLinkingIOS',
'RCTNetwork',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTWebSocket'
]

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end

target 'groc2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for groc2

  target 'groc2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSVG', :path => '../node_modules/react-native-svg'


    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  end

  target 'groc2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
